# install Nginx
# yum install nginx -y 
- name: Install nginx
  ansible.builtin.yum:
    name: nginx
    state: installed


#DONE
# Remove the default content that web server is serving.
# rm -rf /usr/share/nginx/html/* 
- name: Remove file (delete file)
  ansible.builtin.file:
    path: /usr/share/nginx/html/*
    state: absent


- name: Create Application Directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory


# Download the frontend content
# curl -o /tmp/frontend.zip https://roboshop-artifacts.s3.amazonaws.com/frontend.zip 
# Extract the frontend content.
# cd /usr/share/nginx/html 
# unzip /tmp/frontend.zip
- name: Unarchive a file that needs to be downloaded (added in 2.0)
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/frontend.zip 
    dest: /usr/share/nginx/html/
    remote_src: yes


# This is created in part filebeat installation and configuration.
#Copying Nginx conf file which holds the log exctracting format 
- name: Create config in nginx for logging format
  ansible.builtin.template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf


# Add the following content - this content created in files folder, ansible structure to hold files.
# Create Nginx Reverse Proxy Configuration.
# vim /etc/nginx/default.d/roboshop.conf 
- name: Create Roboshop config in Nginx
  ansible.builtin.template:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf

    #Note: Instead of copy from ansible.builtin.copy, we updated with temlates, 
    #however /files renamed with /tmeplate in folder structure


# Start & Enable Nginx service
# systemctl enable nginx 
# systemctl start nginx 
- name: Restart Nginx service
  ansible.builtin.systemd:
    name: nginx
    state: restarted
    enabled: yes
    daemon-reload: yes


# NOTE
# Ensure you replace the localhost with the actual ip address of those component server. 
#Word localhost is just used to avoid the failures on the Nginx Server.

#SOLUTION: this has to be update on roboshop.conf file.

# Restart Nginx Service to load the changes of the configuration.
# systemctl restart nginx 

#SOLUTION: usying systemd build module, can be restarted service and enabled, see abvoe.