# Configure YUM Repos from the script provided by vendor.
# curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | bash
- name: Setup Earling Repos
  ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | bash


# Configure YUM Repos for RabbitMQ.
# curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | bash
- name: Install RabbitMQ Repos
  ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | bash


# Install RabbitMQ
# #yum install rabbitmq-server -y 
# - name: install Earling and RabbitMQ
#   ansible.builtin.yum:
#     name:
#       - rabbitmq-server
#       - erlang
#     state: installed

# replace above in below
- name: install Earling and RabbitMQ
  ansible.builtin.yum:
    name: "{{ packages }}"
  vars:
    packages:
    - rabbitmq-server
    - erlang-21.3.8.15-1.el8.x86_64


# systemctl enable rabbitmq-server 
# systemctl start rabbitmq-server 
# Start RabbitMQ Service
- name: Start RabbitMQ service
  ansible.builtin.systemd:
    name: rabbitmq-server
    state: started
    enabled: yes

# RabbitMQ comes with a default username / password as guest/guest. 
#But this user cannot be used to connect. Hence, we need to create one user for the application.
# rabbitmqctl add_user roboshop roboshop123
# rabbitmqctl set_permissions -p / roboshop ".*" ".*" ".*"
- name: add application user
  community.rabbitmq.rabbitmq_user:
    user: roboshop
    password: roboshop123
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present