# - name: Install java-1.8.0-openjdk.x86_64
#   ansible.builtin.yum:
#     name: java-1.8.0-openjdk.x86_64
#     state: installed

# repo file copied into application service(i.e frontend) machine
- name: copy Elastic repo file in service 
  ansible.builtin.template:
    src: elastic.repo
    dest: /etc/yum.repos.d/elastic.repo

- name: Install and enable elasticsearch
  ansible.builtin.yum:
    name: elasticsearch
    state: installed

- name: Copy config servie to SystemD service
  ansible.builtin.template:
    src: elasticsearch.yml
    dest: /etc/elasticsearch/elasticsearch.yml

# - name: Starting ElasticSearch service
#   ansible.builtin.systemd:
#     name: elasticsearch
#     state: started
#     enabled: yes

- name: Restart and enable Elastic service
  ansible.builtin.service:
    name: elasticsearch.service
    state: started
    enabled: true
    daemon-reload: true

# - name: Install and kibana
#   ansible.builtin.yum:
#     name: kibana
#     state: installed


# - name: copy Elastic service file
#   ansible.builtin.template:
#     src: elasticsearch.service
#     dest: /usr/lib/systemd/system/elasticsearch.service
    

# - name: Copy config servie to SystemD service
#   ansible.builtin.template:
#     src: elasticsearch.yml
#     dest: /etc/elasticsearch/elasticsearch.yml

# - name: Restart and enable Elastic service
#   ansible.builtin.systemd:
#     name: elasticsearch
#     state: started
#     # enabled: true
#     # daemon-reload: true


# - name: Install and enable kibana
#   ansible.builtin.systemd:
#     name: kibana
#     state: restarted
#     enabled: yes
#     daemon-reload: yes