# CentOS-8 Comes with MySQL 8 Version by default, However our application needs MySQL 5.7. So lets disable MySQL 8 version.
# yum module disable mysql -y 
- name: My SQL disable uninstall default version 8
  ansible.builtin.shell: dnf module disable mysql -y


# Setup the MySQL5.7 repo file
# Install MySQL Server
# yum install mysql-community-server -y
- name: Install Mysql 5.7 version
  ansible.builtin.yum:
    name: mysql-community-server
    state: installed


# /etc/yum.repos.d/mysql.repo
# [mysql]
# name=MySQL 5.7 Community Server
# baseurl=http://repo.mysql.com/yum/mysql-5.7-community/el/7/$basearch/
# enabled=1
# gpgcheck=0
- name: Setup Mysql Repos
  ansible.builtin.copy:
    src: mysql.repo
    dest: /etc/yum.repos.d/mysql.repo
    disable_gpg_check: yes


# Start MySQL Service
# systemctl enable mysqld
# systemctl start mysqld 
- name: Start Mysql Service
  ansible.builtin.systemd:
    name: mysqld
    state: started
    enabled: yes


# Next, We need to change the default root password in order to start using the database service. 
#Use password RoboShop@1 or any other as per your choice.
# mysql_secure_installation --set-root-pass RoboShop@1
- name: Set root password
  ansible.builtin.shell: mysql_secure_installation --set-root-pass RoboShop@1
  ignore_errors: yes
  #it throughs error when it try to set pwd which is already reset 
  

# You can check the new password working or not using the following command in MySQL.
# mysql -uroot -pRoboShop@1