
#Alerts Manager Installation
# WIP
- name: Alerts Manager Installation
  ansible.builtin.unarchive:
    src: "{{ alerts_manager_url }}"
    dest: /opt
    remote_src: true

#Alerts Manager Installation
- name: Copy Alerts Manager Service file to systemD exporter
  ansible.builtin.template:
    src: alertmanager.service
    dest: /etc/systemd/system/alertmanager.service
    remote_src: true

##Alert Manager Configuraiton
- name: Update Alert manager configuraiton
  ansible.builtin.template:
    src: alertmanager.yml
    dest: /opt/{{alert_manager_dir}}/alertmanager.yml

#Alert Manager restart
- name: Restart AlertManager 
  ansible.builtin.systemd:
    name: alertmanager
    state: restarted
    enabled: true
    daemon-reload: true

#Check alert manager is started
- name: Check Alertmanager is started
  ansible.builtin.shell: netstat -lntp | grep 9093