- name: Prometheus Node Exporter in roboshop instance
  ansible.builtin.unarchive:
    src: "{{ exporter_url }}"
    dest: /opt
    remote_src: true

# Service file placed from template folder
- name: Copy systemD exporter
  ansible.builtin.template:
    src: exporter.service
    dest: /etc/systemd/system/node_exporter.service

#now serive starting based on template file placed in
- name: Starting Exporter Service
  ansible.builtin.systemd:
    name: node_exporter
    state: restarted
    enabled: yes
    daemon-reload: yes
