- name: Update Grafana Repo
  ansible.builtin.template:
    src: grafana.repo
    dest: /etc/yum.repos.d/grafana.repo
    remote_src: true

- name: Grafana Installation
  ansible.builtin.yum:
    name: grafana
    state: installed

- name: start and enable grafana
  ansible.builtin.systemd:
    name: grafana-server
    state: started
    enabled: true


#EnvironmentFile=/etc/sysconfig/grafana-server



# - name: wait for service up
#   uri:
#     url: "http://127.0.0.1:3000"
#     status_code: 200
#   register: __result
#   until: __result.status == 200
#   retries: 120
#   delay: 1