- name: Update Grafana Repo
  ansible.builtin.template:
    src: grafana.repo
    dest: /etc/yum.repos.d/grafana.repo
    remote_src: true

- name: Grafana Installation
  ansible.builtin.yum:
    name: grafana
    state: installed

- name: Restart Prometheus
  ansible.builtin.systemd:
    name: grafana
    state: started
    enabled: true