- name: Update Grafana Repo
  ansible.builtin.template:
    src: grafana.rep
    dest: /etc/yum.repos.d/grafana.repo

- name: Grafana Installation
  ansible.builtin.yum:
    name: grafana-8.5.6-1
    state: installed

- name: Restart Prometheus
  ansible.builtin.systemd:
    name: grafana
    state: started
    enabled: true