- name: Prometheus Server
  ansible.builtin.import_tasks:
    file: server.yml
    # it only run when prometheus_server is set to true
  when: prometheus_server

- name: Prometheus Server
  ansible.builtin.import_tasks:
    file: exporter.yml
    # it only run when prometheus_server is set to true
  when: node_exporter