
- name: Create App directory Directory
  ansible.builtin.file:
    path: /opt/prometheus
    state: directory

- name: Update Prometheus configuration
  ansible.builtin.template:
    src: prometheus.yml
    dest: /opt/prometheus/prometheus.yml

# as you updated config abvoe need a restart
- name: Restart Prometheus
  ansible.builtin.systemd:
    name: prometheus
    state: restarted
    enabled: true
    daemon-reload: true