- name: Prometheus server Installation
  ansible.builtin.unarchive:
    src: "{{ prometheus_server_url }}"
    dest: /opt
    remote_src: true

# Service file placed from template folder
- name: Copy Prometheus Service file to systemD exporter
  ansible.builtin.template:
    src: prometheus.service
    dest: /etc/systemd/system/prometheus.service
    remote_src: true

# - name: Create App directory Directory
#   ansible.builtin.file:
#     path: /opt/prometheus
#     state: directory

- name: Update Prometheus configuration
  ansible.builtin.template:
    src: prometheus.yml
    dest: /opt/prometheus/prometheus.yml

# as you updated config abvoe need a restart
- name: Restart Prometheus
  ansible.builtin.systemd:
    name: prometheus
    state: restarted
    enabled: true
    daemon-reload: true