#  print_head "create roboshop ${component}"
#     id roboshop &>>${log_file}
#     if [ $? -ne 0 ]; then
#         useradd roboshop &>>${log_file}
#     fi
#     status_check $?

- name: Create Application user
  ansible.builtin.user:
    name: roboshop

#     print_head "create app directory"
#     if [ ! -d /app ]; then
#         mkdir /app &>>${log_file}
#     fi
#     status_check $?

- name: Craeate App directory
  ansible.builtin.file:
    name: /app
    state: directory


#     print_head "remove old log content"
#     rm -rf /app/* &>>${log_file}
#     status_check $?
- name: Remove file (delete file)
  ansible.builtin.file:
    path: /app/*
    state: absent


#     print_head "download app content"
#     curl -o /tmp/${component}.zip https://roboshop-artifacts.s3.amazonaws.com/${component}.zip &>>${log_file}
#     status_check $?
#     cd /app 
#     print_head "extracting app content"
#     unzip /tmp/${component}.zip &>>${log_file}
#     status_check $?

- name: Download {{ component }} content and extracting
  ansible.builtin.unarchive: 
    src: https://roboshop-artifacts.s3.amazonaws.com/{{ component }}.zip
    dest: /app
    state: installed
