#  print_head "create roboshop ${component}"
#     id roboshop &>>${log_file}
#     if [ $? -ne 0 ]; then
#         useradd roboshop &>>${log_file}
#     fi
#     status_check $?

- name: Create Application user
  ansible.builtin.user:
    name: roboshop

#     print_head "create app directory"
#     if [ ! -d /app ]; then
#         mkdir /app &>>${log_file}
#     fi
#     status_check $?

- name: Delete App directory
  ansible.builtin.file:
    name: /app
    state: absent

- name: Create App directory
  ansible.builtin.file:
    name: /app
    state: directory


#     print_head "remove old log content"
#     rm -rf /app/* &>>${log_file}
#     status_check $?

#     print_head "download app content"
#     curl -o /tmp/${component}.zip https://roboshop-artifacts.s3.amazonaws.com/${component}.zip &>>${log_file}
#     status_check $?
#     cd /app 
#     print_head "extracting app content"
#     unzip /tmp/${component}.zip &>>${log_file}
#     status_check $?

# DOWNLOAD - from S3 BUCKET.
# - name: Download {{ component }} content and extracting
#   ansible.builtin.unarchive: 
#     src: https://roboshop-artifacts.s3.amazonaws.com/{{ component }}.zip
#     dest: /app
#     remote_src: true 

#Commented Above AWS donwload. 
# NOW ALL APP CODE POINTING TO NEXUS REPO. 
- name: Download {{ component }} content and extracting
  ansible.builtin.unarchive: 
    src: http://{{ lookup('aws_ssm', '{{env}}.nexus.user', region='us-east-1') }}:{{ lookup('aws_ssm', '{{env}}.nexus.pass', region='us-east-1') }}@nexus.devopsforyou.online:8081/repository/{{component}}/{{component}}-{{app_version}}.zip
    dest: /app
    remote_src: true 