# print_head "Installing golang"
#     yum install golang -y &>>${log_file}
#     status_check $?
- name: Install golang for dispatch service
  ansible.builtin.yum:
    name: golang
    state: installed


#     #prereq function
#     app_prereq_setup
- name: Load App prerequisite from another task
  ansible.builtin.import_tasks:
    file: app-prereq.yml

#     Go to /app folder then run shell commands
#     print_head "Donwload Dependencies & Packages"
#     go mod init dispatch &>>${log_file}
#     go get &>>${log_file}
#     go build &>>${log_file}
#     status_check $?

- name: GoLang Installation
  ansible.builtin.shell: go mod init dispatch ; go get ; go build
  args:
    chdir: /app

#     #systemd setup function
#     systemd_setup
- name: SystemD setup
  ansible.builtin.import_tasks:
    file: systemd-setup.yml

