- name: Setup hostname
  ansible.builtin.shell: set-hostname {{ component }}

#command addon installation aread where we can creaet comman roles then used in each service based roels
#form frontend to dispatch)
- name: Install Node Exporter
  ansible.builtin.import_role:
    name: prometheus
    #exporter yml file is being called to execute
    tasks_from: exporter
  when: node_exporter

# Calling elk role for each component to get in installed filebeat
- name: Install filebeat on each component
  ansible.builtin.import_role:
    name: elk
    #filebeat yml file is being called to execute
    tasks_from: filebeat
  when: filebeat