##This App_version variable will take priority than the same variable in each component of 
## defaults folder. Variable priority Default is least priority than vars folder.
app_version: "{{ lookup('aws_ssm', '{{env}}.{{component}}.app_verion', region='us-east-1') }}"
